// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: pb/storer.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type None struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
}

func (x *None) Reset() {
	*x = None{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *None) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*None) ProtoMessage() {}

func (x *None) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use None.ProtoReflect.Descriptor instead.
func (*None) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{0}
}

func (x *None) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

type Int8 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Value    []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Int8) Reset() {
	*x = Int8{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int8) ProtoMessage() {}

func (x *Int8) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int8.ProtoReflect.Descriptor instead.
func (*Int8) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{1}
}

func (x *Int8) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Int8) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Int64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Value    int64  `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Int64) Reset() {
	*x = Int64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64) ProtoMessage() {}

func (x *Int64) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64.ProtoReflect.Descriptor instead.
func (*Int64) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{2}
}

func (x *Int64) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Int64) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Bytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Value    []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Bytes) Reset() {
	*x = Bytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytes) ProtoMessage() {}

func (x *Bytes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytes.ProtoReflect.Descriptor instead.
func (*Bytes) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{3}
}

func (x *Bytes) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Bytes) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ModuleNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=Names,proto3" json:"Names,omitempty"`
}

func (x *ModuleNames) Reset() {
	*x = ModuleNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleNames) ProtoMessage() {}

func (x *ModuleNames) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleNames.ProtoReflect.Descriptor instead.
func (*ModuleNames) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{4}
}

func (x *ModuleNames) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type ModuleName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ModuleName) Reset() {
	*x = ModuleName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleName) ProtoMessage() {}

func (x *ModuleName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleName.ProtoReflect.Descriptor instead.
func (*ModuleName) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{5}
}

func (x *ModuleName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath   string          `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Remotes    []*MapRemotes   `protobuf:"bytes,2,rep,name=Remotes,proto3" json:"Remotes,omitempty"`
	Submodules []*MapSubmodule `protobuf:"bytes,3,rep,name=Submodules,proto3" json:"Submodules,omitempty"`
	Branches   []*MapBranch    `protobuf:"bytes,4,rep,name=Branches,proto3" json:"Branches,omitempty"`
	Raw        *Config         `protobuf:"bytes,5,opt,name=Raw,proto3" json:"Raw,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{6}
}

func (x *Config) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Config) GetRemotes() []*MapRemotes {
	if x != nil {
		return x.Remotes
	}
	return nil
}

func (x *Config) GetSubmodules() []*MapSubmodule {
	if x != nil {
		return x.Submodules
	}
	return nil
}

func (x *Config) GetBranches() []*MapBranch {
	if x != nil {
		return x.Branches
	}
	return nil
}

func (x *Config) GetRaw() *Config {
	if x != nil {
		return x.Raw
	}
	return nil
}

type MapBranch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Branch *Branch `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
}

func (x *MapBranch) Reset() {
	*x = MapBranch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapBranch) ProtoMessage() {}

func (x *MapBranch) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapBranch.ProtoReflect.Descriptor instead.
func (*MapBranch) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{7}
}

func (x *MapBranch) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapBranch) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type Branch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Remote string      `protobuf:"bytes,2,opt,name=Remote,proto3" json:"Remote,omitempty"`
	Merge  string      `protobuf:"bytes,3,opt,name=Merge,proto3" json:"Merge,omitempty"`
	Rebase string      `protobuf:"bytes,4,opt,name=Rebase,proto3" json:"Rebase,omitempty"`
	Raw    *Subsection `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *Branch) Reset() {
	*x = Branch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{8}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *Branch) GetMerge() string {
	if x != nil {
		return x.Merge
	}
	return ""
}

func (x *Branch) GetRebase() string {
	if x != nil {
		return x.Rebase
	}
	return ""
}

func (x *Branch) GetRaw() *Subsection {
	if x != nil {
		return x.Raw
	}
	return nil
}

type MapSubmodule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Sub *Submodule `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
}

func (x *MapSubmodule) Reset() {
	*x = MapSubmodule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapSubmodule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSubmodule) ProtoMessage() {}

func (x *MapSubmodule) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSubmodule.ProtoReflect.Descriptor instead.
func (*MapSubmodule) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{9}
}

func (x *MapSubmodule) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapSubmodule) GetSub() *Submodule {
	if x != nil {
		return x.Sub
	}
	return nil
}

type Submodule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	RepoPath string      `protobuf:"bytes,2,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	URL      string      `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	Branch   string      `protobuf:"bytes,4,opt,name=Branch,proto3" json:"Branch,omitempty"`
	Raw      *Subsection `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *Submodule) Reset() {
	*x = Submodule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Submodule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submodule) ProtoMessage() {}

func (x *Submodule) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submodule.ProtoReflect.Descriptor instead.
func (*Submodule) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{10}
}

func (x *Submodule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Submodule) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Submodule) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *Submodule) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Submodule) GetRaw() *Subsection {
	if x != nil {
		return x.Raw
	}
	return nil
}

type MapRemotes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Config *RemoteConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *MapRemotes) Reset() {
	*x = MapRemotes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapRemotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRemotes) ProtoMessage() {}

func (x *MapRemotes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRemotes.ProtoReflect.Descriptor instead.
func (*MapRemotes) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{11}
}

func (x *MapRemotes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapRemotes) GetConfig() *RemoteConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RemoteConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	URLs  []string    `protobuf:"bytes,2,rep,name=URLs,proto3" json:"URLs,omitempty"`
	Fetch []string    `protobuf:"bytes,3,rep,name=Fetch,proto3" json:"Fetch,omitempty"`
	Raw   *Subsection `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *RemoteConfig) Reset() {
	*x = RemoteConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteConfig) ProtoMessage() {}

func (x *RemoteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteConfig.ProtoReflect.Descriptor instead.
func (*RemoteConfig) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{12}
}

func (x *RemoteConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteConfig) GetURLs() []string {
	if x != nil {
		return x.URLs
	}
	return nil
}

func (x *RemoteConfig) GetFetch() []string {
	if x != nil {
		return x.Fetch
	}
	return nil
}

func (x *RemoteConfig) GetRaw() *Subsection {
	if x != nil {
		return x.Raw
	}
	return nil
}

type Subsection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string           `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Options []*MapFieldEntry `protobuf:"bytes,2,rep,name=Options,proto3" json:"Options,omitempty"`
}

func (x *Subsection) Reset() {
	*x = Subsection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subsection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subsection) ProtoMessage() {}

func (x *Subsection) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subsection.ProtoReflect.Descriptor instead.
func (*Subsection) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{13}
}

func (x *Subsection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subsection) GetOptions() []*MapFieldEntry {
	if x != nil {
		return x.Options
	}
	return nil
}

type ReferenceName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ReferenceName) Reset() {
	*x = ReferenceName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferenceName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceName) ProtoMessage() {}

func (x *ReferenceName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceName.ProtoReflect.Descriptor instead.
func (*ReferenceName) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{14}
}

func (x *ReferenceName) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *ReferenceName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string   `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Version  uint32   `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Entries  []*Entry `protobuf:"bytes,3,rep,name=Entries,proto3" json:"Entries,omitempty"`
	Cache    *Tree    `protobuf:"bytes,4,opt,name=Cache,proto3" json:"Cache,omitempty"`
}

func (x *Index) Reset() {
	*x = Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{15}
}

func (x *Index) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Index) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Index) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Index) GetCache() *Tree {
	if x != nil {
		return x.Cache
	}
	return nil
}

type ResolveUndo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ResolveUndoEntry `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
}

func (x *ResolveUndo) Reset() {
	*x = ResolveUndo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveUndo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUndo) ProtoMessage() {}

func (x *ResolveUndo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUndo.ProtoReflect.Descriptor instead.
func (*ResolveUndo) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveUndo) GetEntries() []*ResolveUndoEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ResolveUndoEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string           `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Entries  []*MapFieldEntry `protobuf:"bytes,2,rep,name=Entries,proto3" json:"Entries,omitempty"`
}

func (x *ResolveUndoEntry) Reset() {
	*x = ResolveUndoEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveUndoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUndoEntry) ProtoMessage() {}

func (x *ResolveUndoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUndoEntry.ProtoReflect.Descriptor instead.
func (*ResolveUndoEntry) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{17}
}

func (x *ResolveUndoEntry) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *ResolveUndoEntry) GetEntries() []*MapFieldEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MapFieldEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   int64  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MapFieldEntry) Reset() {
	*x = MapFieldEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapFieldEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFieldEntry) ProtoMessage() {}

func (x *MapFieldEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFieldEntry.ProtoReflect.Descriptor instead.
func (*MapFieldEntry) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{18}
}

func (x *MapFieldEntry) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *MapFieldEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Tree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*TreeEntry `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
}

func (x *Tree) Reset() {
	*x = Tree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{19}
}

func (x *Tree) GetEntries() []*TreeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type TreeEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Entries  int64  `protobuf:"varint,2,opt,name=Entries,proto3" json:"Entries,omitempty"`
	Trees    int64  `protobuf:"varint,3,opt,name=Trees,proto3" json:"Trees,omitempty"`
	Hash     string `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *TreeEntry) Reset() {
	*x = TreeEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeEntry) ProtoMessage() {}

func (x *TreeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeEntry.ProtoReflect.Descriptor instead.
func (*TreeEntry) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{20}
}

func (x *TreeEntry) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *TreeEntry) GetEntries() int64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *TreeEntry) GetTrees() int64 {
	if x != nil {
		return x.Trees
	}
	return 0
}

func (x *TreeEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash         string `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt    int64  `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	ModifiedAt   int64  `protobuf:"varint,4,opt,name=ModifiedAt,proto3" json:"ModifiedAt,omitempty"`
	Dev          uint32 `protobuf:"varint,5,opt,name=Dev,proto3" json:"Dev,omitempty"`
	Inode        uint32 `protobuf:"varint,6,opt,name=Inode,proto3" json:"Inode,omitempty"`
	Mode         uint32 `protobuf:"varint,7,opt,name=Mode,proto3" json:"Mode,omitempty"`
	UID          uint32 `protobuf:"varint,8,opt,name=UID,proto3" json:"UID,omitempty"`
	GID          uint32 `protobuf:"varint,9,opt,name=GID,proto3" json:"GID,omitempty"`
	Size         uint32 `protobuf:"varint,10,opt,name=Size,proto3" json:"Size,omitempty"`
	Stage        int64  `protobuf:"varint,11,opt,name=Stage,proto3" json:"Stage,omitempty"`
	SkipWorktree bool   `protobuf:"varint,12,opt,name=SkipWorktree,proto3" json:"SkipWorktree,omitempty"`
	IntentToAdd  bool   `protobuf:"varint,13,opt,name=IntentToAdd,proto3" json:"IntentToAdd,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{21}
}

func (x *Entry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Entry) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *Entry) GetDev() uint32 {
	if x != nil {
		return x.Dev
	}
	return 0
}

func (x *Entry) GetInode() uint32 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Entry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Entry) GetUID() uint32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Entry) GetGID() uint32 {
	if x != nil {
		return x.GID
	}
	return 0
}

func (x *Entry) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Entry) GetStage() int64 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Entry) GetSkipWorktree() bool {
	if x != nil {
		return x.SkipWorktree
	}
	return false
}

func (x *Entry) GetIntentToAdd() bool {
	if x != nil {
		return x.IntentToAdd
	}
	return false
}

type Hashs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string   `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	Hash     []string `protobuf:"bytes,2,rep,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *Hashs) Reset() {
	*x = Hashs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hashs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashs) ProtoMessage() {}

func (x *Hashs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashs.ProtoReflect.Descriptor instead.
func (*Hashs) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{22}
}

func (x *Hashs) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Hashs) GetHash() []string {
	if x != nil {
		return x.Hash
	}
	return nil
}

// EncodedObject.Hash
type EncodedObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Type []byte `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"` // uint8
	Size int64  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *EncodedObject) Reset() {
	*x = EncodedObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedObject) ProtoMessage() {}

func (x *EncodedObject) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedObject.ProtoReflect.Descriptor instead.
func (*EncodedObject) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{23}
}

func (x *EncodedObject) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EncodedObject) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *EncodedObject) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Reference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	T        []byte `protobuf:"bytes,2,opt,name=T,proto3" json:"T,omitempty"`
	N        string `protobuf:"bytes,3,opt,name=N,proto3" json:"N,omitempty"`
	H        string `protobuf:"bytes,4,opt,name=H,proto3" json:"H,omitempty"`
	Target   string `protobuf:"bytes,5,opt,name=Target,proto3" json:"Target,omitempty"`
}

func (x *Reference) Reset() {
	*x = Reference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{24}
}

func (x *Reference) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Reference) GetT() []byte {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Reference) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *Reference) GetH() string {
	if x != nil {
		return x.H
	}
	return ""
}

func (x *Reference) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type References struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Refs []*Reference `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
}

func (x *References) Reset() {
	*x = References{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *References) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*References) ProtoMessage() {}

func (x *References) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use References.ProtoReflect.Descriptor instead.
func (*References) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{25}
}

func (x *References) GetRefs() []*Reference {
	if x != nil {
		return x.Refs
	}
	return nil
}

type SetReferenceParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string     `protobuf:"bytes,1,opt,name=RepoPath,proto3" json:"RepoPath,omitempty"`
	New      *Reference `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	Old      *Reference `protobuf:"bytes,3,opt,name=old,proto3" json:"old,omitempty"`
}

func (x *SetReferenceParams) Reset() {
	*x = SetReferenceParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetReferenceParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceParams) ProtoMessage() {}

func (x *SetReferenceParams) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceParams.ProtoReflect.Descriptor instead.
func (*SetReferenceParams) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{26}
}

func (x *SetReferenceParams) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *SetReferenceParams) GetNew() *Reference {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *SetReferenceParams) GetOld() *Reference {
	if x != nil {
		return x.Old
	}
	return nil
}

type Config_Core struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsBare      bool   `protobuf:"varint,1,opt,name=IsBare,proto3" json:"IsBare,omitempty"`
	Worktree    string `protobuf:"bytes,2,opt,name=Worktree,proto3" json:"Worktree,omitempty"`
	CommentChar string `protobuf:"bytes,3,opt,name=CommentChar,proto3" json:"CommentChar,omitempty"`
}

func (x *Config_Core) Reset() {
	*x = Config_Core{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Core) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Core) ProtoMessage() {}

func (x *Config_Core) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Core.ProtoReflect.Descriptor instead.
func (*Config_Core) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Config_Core) GetIsBare() bool {
	if x != nil {
		return x.IsBare
	}
	return false
}

func (x *Config_Core) GetWorktree() string {
	if x != nil {
		return x.Worktree
	}
	return ""
}

func (x *Config_Core) GetCommentChar() string {
	if x != nil {
		return x.CommentChar
	}
	return ""
}

type Config_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *Config_User) Reset() {
	*x = Config_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_User) ProtoMessage() {}

func (x *Config_User) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_User.ProtoReflect.Descriptor instead.
func (*Config_User) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Config_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Config_Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *Config_Author) Reset() {
	*x = Config_Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Author) ProtoMessage() {}

func (x *Config_Author) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Author.ProtoReflect.Descriptor instead.
func (*Config_Author) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{6, 2}
}

func (x *Config_Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config_Author) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Config_Committer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *Config_Committer) Reset() {
	*x = Config_Committer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Committer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Committer) ProtoMessage() {}

func (x *Config_Committer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Committer.ProtoReflect.Descriptor instead.
func (*Config_Committer) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{6, 3}
}

func (x *Config_Committer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config_Committer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Config_Pack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Window uint64 `protobuf:"varint,1,opt,name=Window,proto3" json:"Window,omitempty"`
}

func (x *Config_Pack) Reset() {
	*x = Config_Pack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storer_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Pack) ProtoMessage() {}

func (x *Config_Pack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storer_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Pack.ProtoReflect.Descriptor instead.
func (*Config_Pack) Descriptor() ([]byte, []int) {
	return file_pb_storer_proto_rawDescGZIP(), []int{6, 4}
}

func (x *Config_Pack) GetWindow() uint64 {
	if x != nil {
		return x.Window
	}
	return 0
}

var File_pb_storer_proto protoreflect.FileDescriptor

var file_pb_storer_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x22, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x22, 0x38, 0x0a, 0x04, 0x49, 0x6e, 0x74,
	0x38, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39,
	0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x20,
	0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0xe4, 0x03, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x52,
	0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52,
	0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x73, 0x12, 0x30, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x75,
	0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x70, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x52, 0x08, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x03, 0x52, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x52, 0x61, 0x77, 0x1a, 0x5c, 0x0a, 0x04,
	0x43, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x42, 0x61, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x42, 0x61, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x57, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x57, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x72, 0x1a, 0x30, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x32, 0x0a, 0x06,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x1a, 0x35, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x1e, 0x0a, 0x04, 0x50, 0x61, 0x63, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x22, 0x41, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x22, 0x84, 0x01, 0x0a, 0x06, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x62, 0x61, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x72, 0x61,
	0x77, 0x22, 0x41, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x53, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x03, 0x73, 0x75, 0x62, 0x22, 0x87, 0x01, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x20, 0x0a, 0x03,
	0x72, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x48,
	0x0a, 0x0a, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28,
	0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x6e, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x52, 0x4c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x55, 0x52, 0x4c, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x20, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x4d, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3f, 0x0a, 0x0d, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x05, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18,
	0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x07, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x0a,
	0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x22, 0x3d, 0x0a,
	0x0b, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x55, 0x6e, 0x64, 0x6f, 0x12, 0x2e, 0x0a, 0x07,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x55, 0x6e, 0x64, 0x6f, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x10,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x55, 0x6e, 0x64, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2b, 0x0a, 0x07,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x0d, 0x4d, 0x61, 0x70,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x2f, 0x0a, 0x04, 0x54, 0x72, 0x65, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x45, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x65, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x09, 0x54, 0x72, 0x65, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x72, 0x65, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x72, 0x65, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x22, 0xbd, 0x02, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x44, 0x65, 0x76, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x44,
	0x65, 0x76, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x47, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x47, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x6b,
	0x69, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x53, 0x6b, 0x69, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64, 0x64,
	0x22, 0x37, 0x0a, 0x05, 0x48, 0x61, 0x73, 0x68, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70,
	0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70,
	0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x4b, 0x0a, 0x0d, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x69, 0x0a, 0x09, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x0c, 0x0a, 0x01, 0x54, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x54, 0x12, 0x0c, 0x0a,
	0x01, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x4e, 0x12, 0x0c, 0x0a, 0x01, 0x48,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x48, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x22, 0x2f, 0x0a, 0x0a, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12,
	0x21, 0x0a, 0x04, 0x72, 0x65, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x04, 0x72, 0x65,
	0x66, 0x73, 0x22, 0x72, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x03, 0x6e, 0x65, 0x77, 0x12, 0x1f, 0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x03, 0x6f, 0x6c, 0x64, 0x32, 0xc2, 0x06, 0x0a, 0x06, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x72, 0x12, 0x31, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x6e, 0x74, 0x38, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x38,
	0x22, 0x00, 0x12, 0x30, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f,
	0x6e, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x12, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x36,
	0x34, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x29, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6e, 0x64, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x32,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x30, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22,
	0x00, 0x12, 0x27, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x6f, 0x73, 0x65, 0x52,
	0x65, 0x66, 0x73, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x08, 0x50, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x66, 0x73, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65,
	0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x0a,
	0x53, 0x65, 0x74, 0x53, 0x68, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x73, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22,
	0x00, 0x12, 0x20, 0x0a, 0x07, 0x53, 0x68, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x73, 0x22, 0x00, 0x12, 0x21, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x09, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x21, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65,
	0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x00, 0x12, 0x23,
	0x0a, 0x09, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e,
	0x65, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x08,
	0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x6f, 0x77, 0x65, 0x72,
	0x6c, 0x61, 0x62, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x69, 0x74, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_storer_proto_rawDescOnce sync.Once
	file_pb_storer_proto_rawDescData = file_pb_storer_proto_rawDesc
)

func file_pb_storer_proto_rawDescGZIP() []byte {
	file_pb_storer_proto_rawDescOnce.Do(func() {
		file_pb_storer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_storer_proto_rawDescData)
	})
	return file_pb_storer_proto_rawDescData
}

var file_pb_storer_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_pb_storer_proto_goTypes = []interface{}{
	(*None)(nil),               // 0: pb.None
	(*Int8)(nil),               // 1: pb.Int8
	(*Int64)(nil),              // 2: pb.Int64
	(*Bytes)(nil),              // 3: pb.Bytes
	(*ModuleNames)(nil),        // 4: pb.ModuleNames
	(*ModuleName)(nil),         // 5: pb.ModuleName
	(*Config)(nil),             // 6: pb.Config
	(*MapBranch)(nil),          // 7: pb.MapBranch
	(*Branch)(nil),             // 8: pb.Branch
	(*MapSubmodule)(nil),       // 9: pb.MapSubmodule
	(*Submodule)(nil),          // 10: pb.Submodule
	(*MapRemotes)(nil),         // 11: pb.MapRemotes
	(*RemoteConfig)(nil),       // 12: pb.RemoteConfig
	(*Subsection)(nil),         // 13: pb.Subsection
	(*ReferenceName)(nil),      // 14: pb.ReferenceName
	(*Index)(nil),              // 15: pb.Index
	(*ResolveUndo)(nil),        // 16: pb.ResolveUndo
	(*ResolveUndoEntry)(nil),   // 17: pb.ResolveUndoEntry
	(*MapFieldEntry)(nil),      // 18: pb.MapFieldEntry
	(*Tree)(nil),               // 19: pb.Tree
	(*TreeEntry)(nil),          // 20: pb.TreeEntry
	(*Entry)(nil),              // 21: pb.Entry
	(*Hashs)(nil),              // 22: pb.Hashs
	(*EncodedObject)(nil),      // 23: pb.EncodedObject
	(*Reference)(nil),          // 24: pb.Reference
	(*References)(nil),         // 25: pb.References
	(*SetReferenceParams)(nil), // 26: pb.SetReferenceParams
	(*Config_Core)(nil),        // 27: pb.Config.Core
	(*Config_User)(nil),        // 28: pb.Config.User
	(*Config_Author)(nil),      // 29: pb.Config.Author
	(*Config_Committer)(nil),   // 30: pb.Config.Committer
	(*Config_Pack)(nil),        // 31: pb.Config.Pack
}
var file_pb_storer_proto_depIdxs = []int32{
	11, // 0: pb.Config.Remotes:type_name -> pb.MapRemotes
	9,  // 1: pb.Config.Submodules:type_name -> pb.MapSubmodule
	7,  // 2: pb.Config.Branches:type_name -> pb.MapBranch
	6,  // 3: pb.Config.Raw:type_name -> pb.Config
	8,  // 4: pb.MapBranch.branch:type_name -> pb.Branch
	13, // 5: pb.Branch.raw:type_name -> pb.Subsection
	10, // 6: pb.MapSubmodule.sub:type_name -> pb.Submodule
	13, // 7: pb.Submodule.raw:type_name -> pb.Subsection
	12, // 8: pb.MapRemotes.config:type_name -> pb.RemoteConfig
	13, // 9: pb.RemoteConfig.raw:type_name -> pb.Subsection
	18, // 10: pb.Subsection.Options:type_name -> pb.MapFieldEntry
	21, // 11: pb.Index.Entries:type_name -> pb.Entry
	19, // 12: pb.Index.Cache:type_name -> pb.Tree
	17, // 13: pb.ResolveUndo.Entries:type_name -> pb.ResolveUndoEntry
	18, // 14: pb.ResolveUndoEntry.Entries:type_name -> pb.MapFieldEntry
	20, // 15: pb.Tree.Entries:type_name -> pb.TreeEntry
	24, // 16: pb.References.refs:type_name -> pb.Reference
	24, // 17: pb.SetReferenceParams.new:type_name -> pb.Reference
	24, // 18: pb.SetReferenceParams.old:type_name -> pb.Reference
	0,  // 19: pb.Storer.NewEncodedObject:input_type -> pb.None
	1,  // 20: pb.Storer.SetEncodedObjectType:input_type -> pb.Int8
	2,  // 21: pb.Storer.SetEncodedObjectSetSize:input_type -> pb.Int64
	0,  // 22: pb.Storer.EncodedObjectReader:input_type -> pb.None
	3,  // 23: pb.Storer.EncodedObjectWriter:input_type -> pb.Bytes
	24, // 24: pb.Storer.SetReference:input_type -> pb.Reference
	26, // 25: pb.Storer.CheckAndSetReference:input_type -> pb.SetReferenceParams
	14, // 26: pb.Storer.GetReference:input_type -> pb.ReferenceName
	0,  // 27: pb.Storer.GetReferences:input_type -> pb.None
	14, // 28: pb.Storer.RemoveReference:input_type -> pb.ReferenceName
	0,  // 29: pb.Storer.CountLooseRefs:input_type -> pb.None
	0,  // 30: pb.Storer.PackRefs:input_type -> pb.None
	22, // 31: pb.Storer.SetShallow:input_type -> pb.Hashs
	0,  // 32: pb.Storer.Shallow:input_type -> pb.None
	15, // 33: pb.Storer.SetIndex:input_type -> pb.Index
	0,  // 34: pb.Storer.GetIndex:input_type -> pb.None
	0,  // 35: pb.Storer.GetConfig:input_type -> pb.None
	6,  // 36: pb.Storer.SetConfig:input_type -> pb.Config
	0,  // 37: pb.Storer.Modules:input_type -> pb.None
	23, // 38: pb.Storer.NewEncodedObject:output_type -> pb.EncodedObject
	1,  // 39: pb.Storer.SetEncodedObjectType:output_type -> pb.Int8
	0,  // 40: pb.Storer.SetEncodedObjectSetSize:output_type -> pb.None
	3,  // 41: pb.Storer.EncodedObjectReader:output_type -> pb.Bytes
	2,  // 42: pb.Storer.EncodedObjectWriter:output_type -> pb.Int64
	0,  // 43: pb.Storer.SetReference:output_type -> pb.None
	0,  // 44: pb.Storer.CheckAndSetReference:output_type -> pb.None
	24, // 45: pb.Storer.GetReference:output_type -> pb.Reference
	25, // 46: pb.Storer.GetReferences:output_type -> pb.References
	0,  // 47: pb.Storer.RemoveReference:output_type -> pb.None
	2,  // 48: pb.Storer.CountLooseRefs:output_type -> pb.Int64
	0,  // 49: pb.Storer.PackRefs:output_type -> pb.None
	0,  // 50: pb.Storer.SetShallow:output_type -> pb.None
	22, // 51: pb.Storer.Shallow:output_type -> pb.Hashs
	0,  // 52: pb.Storer.SetIndex:output_type -> pb.None
	15, // 53: pb.Storer.GetIndex:output_type -> pb.Index
	6,  // 54: pb.Storer.GetConfig:output_type -> pb.Config
	0,  // 55: pb.Storer.SetConfig:output_type -> pb.None
	4,  // 56: pb.Storer.Modules:output_type -> pb.ModuleNames
	38, // [38:57] is the sub-list for method output_type
	19, // [19:38] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pb_storer_proto_init() }
func file_pb_storer_proto_init() {
	if File_pb_storer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_storer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*None); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int8); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapBranch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Branch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapSubmodule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Submodule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapRemotes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subsection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferenceName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveUndo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveUndoEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapFieldEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreeEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hashs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*References); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetReferenceParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Core); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Committer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storer_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Pack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_storer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_storer_proto_goTypes,
		DependencyIndexes: file_pb_storer_proto_depIdxs,
		MessageInfos:      file_pb_storer_proto_msgTypes,
	}.Build()
	File_pb_storer_proto = out.File
	file_pb_storer_proto_rawDesc = nil
	file_pb_storer_proto_goTypes = nil
	file_pb_storer_proto_depIdxs = nil
}
